### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sunithak** [hrbrmstr/uaparserjs#2]
> devtools::install_github("hrbrmstr/uaparserjs")
Downloading GitHub repo hrbrmstr/uaparserjs@master
from URL https://api.github.com/repos/hrbrmstr/uaparserjs/zipball/master
Installing uaparserjs
'/usr/lib64/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/Rtmp9cUoOY/devtoolscea3eebfee3/hrbrmstr-uaparserjs-ecdc86c' --library='/home/sunitha/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests --no-multiarch 

* installing *source* package ‘uaparserjs’ ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
sh: line 1:   926 Segmentation fault      (core dumped) '/usr/lib64/R/bin/R' --no-save --slave 2>&1 < '/tmp/RtmpMgATn9/file3977406c9ec'

 *** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: .Call("V8_make_context", PACKAGE = "V8", set_console)
 2: make_context(private$console)
 3: reset()
 4: eval(quote({    eval <- function(src) {        get_str_output(context_eval(join(src), private$context))    }    validate <- function(src) {        context_validate(join(src), private$context)    }    call <- function(fun, ..., auto_unbox = TRUE) {        stopifnot(is.character(fun))        stopifnot(this$validate(c("fun=", fun)))        jsargs <- list(...)        if (!is.null(names(jsargs))) {            stop("Named arguments are not supported in JavaScript.")        }        jsargs <- vapply(jsargs, function(x) {            if (is.atomic(x) && inherits(x, "JS_EVAL")) {                as.character(x)            } else {                toJSON(x, auto_unbox = auto_unbox)            }        }, character(1))        jsargs <- paste(jsargs, collapse = ",")        src <- paste0("JSON.stringify((", fun, ")(", jsargs,             "));")        out <- this$eval(src)        get_json_output(out)    }    source <- function(file) {        if (is.character(file) && length(file) == 1 && grepl("^https?://",             file)) {            file <- curl(file, open = "r")            on.exit(close(file))        }        this$eval(readLines(file, encoding = "UTF-8", warn = FALSE))    }    get <- function(name, ...) {        stopifnot(is.character(name))        get_json_output(this$eval(c("JSON.stringify(", name,             ")")), ...)    }    assign <- function(name, value, auto_unbox = TRUE, ...) {        stopifnot(is.character(name))        obj <- if (inherits(value, "JS_EVAL")) {            invisible(this$eval(paste("var", name, "=", value)))        } else {            invisible(this$eval(paste("var", name, "=", toJSON(value,                 auto_unbox = auto_unbox, ...))))        }    }    reset <- function() {        private$context <- make_context(private$console)        private$created <- Sys.time()        if (length(global)) {            context_eval(paste("var", global, "= this;", collapse = "\n"),                 private$context)        }        if (isTRUE(typed_arrays)) {            context_enable_typed_arrays(private$context)        }        invisible()    }    console <- function() {        this$eval("")        message("This is V8 version ", version(), ". Press ESC or CTRL+C to exit.")        on.exit(message("Exiting V8 console."))        buffer <- character()        has_history <- !inherits(try(savehistory(tempfile()),             silent = T), "try-error")        if (has_history) {            savehistory()            on.exit(loadhistory(), add = TRUE)            histfile <- ".V8history"            if (file.exists(histfile)) {                loadhistory(histfile)            } else {                file.create(histfile)            }        }        rc.options(custom.completer = function(env) {            env$comps <- tab_complete(this, env$token)        })        on.exit({            rc.options(custom.completer = NULL)        }, add = TRUE)        repeat {            prompt <- ifelse(length(buffer), "  ", "~ ")            if (nchar(line <- readline(prompt))) {                buffer <- c(buffer, line)            }            if (identical(buffer, "exit")) break            if (length(buffer) && (this$validate(buffer) || !nchar(line))) {                if (has_history) {                  write(buffer, histfile, append = TRUE)                  loadhistory(histfile)                }                tryCatch(cat(undefined_to_null(this$eval(buffer))),                   error = function(e) {                    message(e$message)                  })                buffer <- character()            }        }    }    reset()    lockEnvironment(environment(), TRUE)    structure(environment(), class = c("V8", "environment"))}), new.env())
 5: eval(quote({    eval <- function(src) {        get_str_output(context_eval(join(src), private$context))    }    validate <- function(src) {        context_validate(join(src), private$context)    }    call <- function(fun, ..., auto_unbox = TRUE) {        stopifnot(is.character(fun))        stopifnot(this$validate(c("fun=", fun)))        jsargs <- list(...)        if (!is.null(names(jsargs))) {            stop("Named arguments are not supported in JavaScript.")        }        jsargs <- vapply(jsargs, function(x) {            if (is.atomic(x) && inherits(x, "JS_EVAL")) {                as.character(x)            } else {                toJSON(x, auto_unbox = auto_unbox)            }        }, character(1))        jsargs <- paste(jsargs, collapse = ",")        src <- paste0("JSON.stringify((", fun, ")(", jsargs,             "));")        out <- this$eval(src)        get_json_output(out)    }    source <- function(file) {        if (is.character(file) && length(file) == 1 && grepl("^https?://",             file)) {            file <- curl(file, open = "r")            on.exit(close(file))        }        this$eval(readLines(file, encoding = "UTF-8", warn = FALSE))    }    get <- function(name, ...) {        stopifnot(is.character(name))        get_json_output(this$eval(c("JSON.stringify(", name,             ")")), ...)    }    assign <- function(name, value, auto_unbox = TRUE, ...) {        stopifnot(is.character(name))        obj <- if (inherits(value, "JS_EVAL")) {            invisible(this$eval(paste("var", name, "=", value)))        } else {            invisible(this$eval(paste("var", name, "=", toJSON(value,                 auto_unbox = auto_unbox, ...))))        }    }    reset <- function() {        private$context <- make_context(private$console)        private$created <- Sys.time()        if (length(global)) {            context_eval(paste("var", global, "= this;", collapse = "\n"),                 private$context)        }        if (isTRUE(typed_arrays)) {            context_enable_typed_arrays(private$context)        }        invisible()    }    console <- function() {        this$eval("")        message("This is V8 version ", version(), ". Press ESC or CTRL+C to exit.")        on.exit(message("Exiting V8 console."))        buffer <- character()        has_history <- !inherits(try(savehistory(tempfile()),             silent = T), "try-error")        if (has_history) {            savehistory()            on.exit(loadhistory(), add = TRUE)            histfile <- ".V8history"            if (file.exists(histfile)) {                loadhistory(histfile)            } else {                file.create(histfile)            }        }        rc.options(custom.completer = function(env) {            env$comps <- tab_complete(this, env$token)        })        on.exit({            rc.options(custom.completer = NULL)        }, add = TRUE)        repeat {            prompt <- ifelse(length(buffer), "  ", "~ ")            if (nchar(line <- readline(prompt))) {                buffer <- c(buffer, line)            }            if (identical(buffer, "exit")) break            if (length(buffer) && (this$validate(buffer) || !nchar(line))) {                if (has_history) {                  write(buffer, histfile, append = TRUE)                  loadhistory(histfile)                }                tryCatch(cat(undefined_to_null(this$eval(buffer))),                   error = function(e) {                    message(e$message)                  })                buffer <- character()            }        }    }    reset()    lockEnvironment(environment(), TRUE)    structure(environment(), class = c("V8", "environment"))}), new.env())
 6: eval(expr, p)
 7: eval(expr, p)
 8: eval.parent(substitute(eval(quote(expr), envir)))
 9: local({    eval <- function(src) {        get_str_output(context_eval(join(src), private$context))    }    validate <- function(src) {        context_validate(join(src), private$context)    }    call <- function(fun, ..., auto_unbox = TRUE) {        stopifnot(is.character(fun))        stopifnot(this$validate(c("fun=", fun)))        jsargs <- list(...)        if (!is.null(names(jsargs))) {            stop("Named arguments are not supported in JavaScript.")        }        jsargs <- vapply(jsargs, function(x) {            if (is.atomic(x) && inherits(x, "JS_EVAL")) {                as.character(x)            }            else {                toJSON(x, auto_unbox = auto_unbox)            }        }, character(1))        jsargs <- paste(jsargs, collapse = ",")        src <- paste0("JSON.stringify((", fun, ")(", jsargs,             "));")        out <- this$eval(src)        get_json_output(out)    }    source <- function(file) {        if (is.character(file) && length(file) == 1 && grepl("^https?://",             file)) {            file <- curl(file, open = "r")            on.exit(close(file))        }        this$eval(readLines(file, encoding = "UTF-8", warn = FALSE))    }    get <- function(name, ...) {        stopifnot(is.character(name))        get_json_output(this$eval(c("JSON.stringify(", name,             ")")), ...)    }    assign <- function(name, value, auto_unbox = TRUE, ...) {        stopifnot(is.character(name))        obj <- if (inherits(value, "JS_EVAL")) {            invisible(this$eval(paste("var", name, "=", value)))        }        else {            invisible(this$eval(paste("var", name, "=", toJSON(value,                 auto_unbox = auto_unbox, ...))))        }    }    reset <- function() {        private$context <- make_context(private$console)        private$created <- Sys.time()        if (length(global)) {            context_eval(paste("var", global, "= this;", collapse = "\n"),                 private$context)        }        if (isTRUE(typed_arrays)) {            context_enable_typed_arrays(private$context)        }        invisible()    }    console <- function() {        this$eval("")        message("This is V8 version ", version(), ". Press ESC or CTRL+C to exit.")        on.exit(message("Exiting V8 console."))        buffer <- character()        has_history <- !inherits(try(savehistory(tempfile()),             silent = T), "try-error")        if (has_history) {            savehistory()            on.exit(loadhistory(), add = TRUE)            histfile <- ".V8history"            if (file.exists(histfile)) {                loadhistory(histfile)            }            else {                file.create(histfile)            }        }        rc.options(custom.completer = function(env) {            env$comps <- tab_complete(this, env$token)        })        on.exit({            rc.options(custom.completer = NULL)        }, add = TRUE)        repeat {            prompt <- ifelse(length(buffer), "  ", "~ ")            if (nchar(line <- readline(prompt))) {                buffer <- c(buffer, line)            }            if (identical(buffer, "exit"))                 break            if (length(buffer) && (this$validate(buffer) || !nchar(line))) {                if (has_history) {                  write(buffer, histfile, append = TRUE)                  loadhistory(histfile)                }                tryCatch(cat(undefined_to_null(this$eval(buffer))),                   error = function(e) {                    message(e$message)                  })                buffer <- character()            }        }    }    reset()    lockEnvironment(environment(), TRUE)    structure(environment(), class = c("V8", "environment"))})
10: v8()
11: fun(libname, pkgname)
12: doTryCatch(return(expr), name, parentenv, handler)
13: tryCatchOne(expr, names, parentenv, handlers[[1L]])
14: tryCatchList(expr, classes, parentenv, handlers)
15: tryCatch(fun(libname, pkgname), error = identity)
16: runHook(".onAttach", ns, dirname(nspath), nsname)
17: attachNamespace(ns, pos = pos, deps)
18: doTryCatch(return(expr), name, parentenv, handler)
19: tryCatchOne(expr, names, parentenv, handlers[[1L]])
20: tryCatchList(expr, classes, parentenv, handlers)
21: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
22: library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE)
23: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
24: suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE))
25: doTryCatch(return(expr), name, parentenv, handler)
26: tryCatchOne(expr, names, parentenv, handlers[[1L]])
27: tryCatchList(expr, classes, parentenv, handlers)
28: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
29: try(suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE)))
30: tools:::.test_load_package("uaparserjs", "/home/sunitha/R/x86_64-pc-linux-gnu-library/3.4")
An irrecoverable exception occurred. R is aborting now ...
ERROR: loading failed
* removing ‘/home/sunitha/R/x86_64-pc-linux-gnu-library/3.4/uaparserjs’
Installation failed: Command failed (1)

**Comment by sunithak** [comment]
Hello, I am trying to install the package in Rstudio. I am getting an error of this. There was a dependency error before to install V(. I did install that. Now this error is coming. I dont know how to deal with it. Please help me regarding this. I am using arch linux and installed v8-3.14

**Comment by hrbrmstr** [comment]
Can you add the output of either `devtools::session_info()`?

**Comment by sunithak** [comment]
> devtools::session_info()
Session info ---------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2017-11-15                  

Packages -------------------------------------------------------------------------------------------------------------------------
 package   * version date       source        
 base      * 3.4.2   2017-09-28 local         
 compiler    3.4.2   2017-09-28 local         
 curl        3.0     2017-10-06 CRAN (R 3.4.2)
 datasets  * 3.4.2   2017-09-28 local         
 devtools    1.13.3  2017-08-02 CRAN (R 3.4.2)
 digest      0.6.12  2017-01-27 CRAN (R 3.4.2)
 git2r       0.19.0  2017-07-19 CRAN (R 3.4.2)
 graphics  * 3.4.2   2017-09-28 local         
 grDevices * 3.4.2   2017-09-28 local         
 httr        1.3.1   2017-08-20 CRAN (R 3.4.2)
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.2)
 methods   * 3.4.2   2017-09-28 local         
 R6          2.2.2   2017-06-17 CRAN (R 3.4.2)
 stats     * 3.4.2   2017-09-28 local         
 tools       3.4.2   2017-09-28 local         
 utils     * 3.4.2   2017-09-28 local         
 withr       2.0.0   2017-07-28 CRAN (R 3.4.2)
 yaml        2.1.14  2016-11-12 CRAN (R 3.4.2)

**Comment by sunithak** [comment]
I was trying every method to solve this error. but not getting through

**Comment by sunithak** [comment]
got another package.. Thank you :)
