### ISSUE TITLE
Unable to install in RStudio

### ISSUE THREAD

**Issue by shatadrusaha** [hrbrmstr/uaparserjs#3]
Hello,

I am trying to install the package, but getting the following error.

> install.packages("uaparserjs")
Warning in install.packages :
  package ‘uaparserjs’ is not available (for R version 3.4.3)

I also noticed the package hasn't been updated since 2016 but the pdf  does say that it is compatible with R (>= 3.0.0). Could someone help me.

Regards

**Comment by hrbrmstr** [comment]
it's in CRAN: https://cran.r-project.org/web/packages/uaparserjs/index.html

if you're on Windows, you need to install from source since there are issues with that terrible operating system and the way memory is allocated to the V8 engine that powers the package.

**Comment by ldanai** [comment]
Hello,

Got the same issue as above.

Also I tried to install from source but still got error. I used Windows 10 and R 3.4.4

Regards,
Danai

`
> install.packages("./packages/uaparserjs_0.1.0.tar.gz", repos = NULL, type="source")
Installing package into ‘C:/Users/ldanai/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
* installing *source* package 'uaparserjs' ...
** package 'uaparserjs' successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
  converting help for package 'uaparserjs'
    finding HTML links ... done
    ua_parse                                html  
    uaparserjs                              html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error: package or namespace load failed for 'uaparserjs':
 .onAttach failed in attachNamespace() for 'uaparserjs', details:
  call: context_eval(join(src), private$context)
  error: RangeError: Maximum call stack size exceeded
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/ldanai/Documents/R/win-library/3.4/uaparserjs'
In R CMD INSTALL
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" CMD INSTALL -l "C:\Users\ldanai\Documents\R\win-library\3.4" "./packages/uaparserjs_0.1.0.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘./packages/uaparserjs_0.1.0.tar.gz’ had non-zero exit status
`

**Comment by randomgambit** [comment]
same error for me on linux this time

> install.packages("uaparserjs", dependencies = TRUE,type = 'source')

I get a `ERROR: configuration failed for package ‘V8’` so the package does not install.

```
* package ‘V8’ successfully unpacked and MD5 sums checked
Using PKG_CFLAGS=-I/usr/include/v8-3.14
Using PKG_LIBS=-lv8
------------------------- ANTICONF ERROR ---------------------------
```Configuration failed because  was not found. Try installing:

**Comment by hrbrmstr** [comment]
It's not the same error. That's a V8 installation error which I (fortunately 😎) have no control over. You'll need to fix that and try again.

The other errors (Windows) are due to the really poorly configured binary DLL installation of V8 for Windows which has super-low settings.

Using this package at-scale is not recommended anyway. I only made it due to the persnikety requirements of https://github.com/ua-parser/uap-r (it's a PITA to compile on macOS and has some serious other C++ dependencies as well).

**Comment by randomgambit** [comment]
ok got it, thanks. I ended up using `user-agent` in python which seems ok
by the way, I would really appreciate your input about my question here https://github.com/hrbrmstr/splashr/issues/18 if you have 3 min :D 

Thanks!!

**Comment by hrbrmstr** [comment]
works on windows now and on cran!
