### ISSUE TITLE
update regex parsing rules from uap-core

### ISSUE THREAD

**Issue by salim-b** [hrbrmstr/uaparserjs#5]
The help file of `ua_parse()` states:

> The regex YAML import date: 2016-08-04

Since that date the [`regexes.yaml`](https://github.com/ua-parser/uap-core/blob/master/regexes.yaml) from `uap-core` has received numerous revisions and I would like to be able to use the latest parsing rules in `uaparserjs`. It [seems the `regexes.yaml` is bundled as base64-encoded JSON](https://github.com/hrbrmstr/uaparserjs/blob/master/inst/js/bundle.js). What would have to be done exactly to update it?

Or maybe the latest [`regexes.yaml` from `uap-core`'s master branch](https://github.com/ua-parser/uap-core/blob/master/regexes.yaml) could even be downloaded and "embedded" automatically when building the package! That way a simple

```r
remotes::install_github(repo = "hrbrmstr/uaparserjs",
                        upgrade = TRUE,
                        force = TRUE)
```
would suffice to get the latest parsing rules :slightly_smiling_face: 

And of course, thanks for developing this package!

**Comment by hrbrmstr** [comment]
long overdude but done and on CRAN even! #ty
