### ISSUE TITLE
Update regex YAML

### ISSUE THREAD

**Issue by xmariona** [hrbrmstr/uaparserjs#7]
Is there any way to update the regex YAML?

**Comment by hrbrmstr** [comment]
thx for flagging! i just pushed up a new release with the latest regexes. there's no good way to let users supply a yaml but i'll see if I can automate updates to the regexes so they're more frequent.

**Comment by xmariona** [comment]
Thank you for your work Bob.

**Comment by hrbrmstr** [comment]
(ty for the ty :-)

Also: thanks to you (honestly, too, since i wld not have gotten to this w/o the ping), the package is also updated on CRAN, works on Windows (thanks to {V8} working better on Windows due to changes in the v8 virtual machine) and I just thinned out the dependencies a bit.
